### ISSUE TITLE
Could not find export.jar (org.grails.plugins:export:2.0.0).

### ISSUE THREAD

**Issue by neerajmalve** [gpc/export#29] opened 2021-04-20 16:28 UTC
Hello,
I see that the plugin folder 2.0.0 is no longer exist on your repo, I can see 2.0.0-SNAPSHOT though, Wanted to know if the plugin repo needs to be changed or if it's depricated. 

thanks
Neeraj

**Comment by neerajmalve** [comment] 2021-04-21 08:05
For now, I have managed it by changing version (Directory name) as below:
`compile "org.grails.plugins:export:2.0.0-SNAPSHOT"
`
But need to have a version of stable version to include.

**Comment by m4rc77** [comment] 2021-04-22 14:30
What is the reason that the files under https://repo.grails.org/grails/core/org/grails/plugins/export/2.0.0/ date from `21-Apr-2021 16:15`? 
**From a plugin that was released `on Jun 29, 2015` I do not expect it to change later!!!**

The download from https://repo.grails.org/grails/core/org/grails/plugins/export/2.0.0/export-2.0.0.jar returns `The requested path was not found` which brakes our build.

Maybe things can be fixed by using the file from our gradle cache ...

**Comment by qvarnis** [comment] 2021-04-23 06:52
> What is the reason that the files under https://repo.grails.org/grails/core/org/grails/plugins/export/2.0.0/ date from `21-Apr-2021 16:15`?
> **From a plugin that was released `on Jun 29, 2015` I do not expect it to change later!!!**
> 
> The download from https://repo.grails.org/grails/core/org/grails/plugins/export/2.0.0/export-2.0.0.jar returns `The requested path was not found` which brakes our build.
> 
> Maybe things can be fixed by using the file from our gradle cache ...

Grails 4.0.10 here, we solved it by getting the jar from gradle-cache and put it in the repo. Then we included thar jar and other stuff that the jar used by doing this:

repositories {
  mavenLocal()
  maven { url "https://repo.grails.org/grails/core" }
  flatDir {
    dirs 'libs'
  }
}

Here libs point to root/libs that we created and put the jar

then in dependencies we did the following:

//Below is a special due to that 'org.grails.plugins:export:2.0.0' was removed from the repo
  //compile 'org.grails.plugins:export:2.0.0'
  implementation name: 'export-2.0.0'
  compile group: 'jexcelapi', name: 'jxl', version: '2.6'
  compile group: 'commons-beanutils', name: 'commons-beanutils', version: '1.9.4'

This worked for us. 

But i agree with you, how the **** can they remove a dependency like this from the central repo?

**Comment by DmitryPrigozhaev** [comment] 2021-04-27 13:07
The problem is also relevant to us. We have been using the dependency in the project for many years, after updating the local cache, we found a build error.

`compile "org.grails.plugins:export:2.0.0"`

We have temporarily solved the problem by placing the dependency in an internal repository. Will it be restored in the central?

Best regards.

**Comment by dwcoltri** [comment] 2021-04-27 17:03
We are also having issues with this. Can we have an ETA for fixing the `export-2.0.0.jar` located `https://repo.grails.org/grails/core/org/grails/plugins/export/2.0.0/`? This is an ongoing issue for us, and I'm sure many others.

**Closed** 2021-07-29 23:49 UTC
